### ISSUE TITLE
Sail + Dusk timeout on clean installation

### ISSUE THREAD

**Issue by mshamaseen** [laravel/dusk#1144]
### Dusk Version

8.2

### Laravel Version

11.28.0

### PHP Version

8.3.12

### PHPUnit Version

11.4.1

### Database Driver & Version

MySql, default sail

### Description

I was trying to setup dusk on an existing project, but it keeps timing out.
so what I did is installed a fresh project to try it, timing out too (when .env.dusk.local exists).

I also see this error on sail console (on the fresh installation):

```
example-app-selenium-1      | 13:47:40.416 ERROR [ThrottlingLogger.doLog] - Failed to export spans. The request could not be executed. Error message: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
example-app-selenium-1      | java.net.ConnectException: Failed to connect to localhost/[0:0:0:0:0:0:0:1]:4317
```

### Steps To Reproduce

1. install fresh project `curl -s https://laravel.build/example-app | bash`
2. cd example-app && sail up -d
3. sail composer require laravel/dusk --dev
4. sail artisan dusk:install
5. Running `sail dusk` now work
6. cp .env .env.dusk.local
7. Running `sail dusk` now does NOT work

trying to sail down and sail up again, still not working. it only work if I removed .env.dusk.local, sail up and sail down again.

**Comment by crynobone** [comment]
Hey there, thanks for reporting this issue.

We'll need more info and/or code to debug this further. Can you please create a repository with the command below, commit the code that reproduces the issue *as one separate commit* on the main/master branch and share the repository here?

Please make sure that you have the [latest version of the Laravel installer](https://github.com/laravel/installer) in order to run this command. Please also make sure you have both Git & [the GitHub CLI tool](https://cli.github.com/) properly set up.

    laravel new bug-report --github="--public"

Do not amend and create a separate commit with your custom changes. After you've posted the repository, we'll try to reproduce the issue.

Thanks!

**Comment by mshamaseen** [comment]
@crynobone here is the repo: https://github.com/mshamaseen/bug-report

**Comment by crynobone** [comment]
Worked fine after setting `APP_URL` and `APP_SERVICE`

![CleanShot 2024-10-22 at 12 22 03](https://github.com/user-attachments/assets/5cf54d9e-8aed-44c5-b7ff-94d8d2686262)
![CleanShot 2024-10-22 at 12 23 08](https://github.com/user-attachments/assets/54591667-160f-420b-9436-a90dc89bc4d3)

**Comment by mshamaseen** [comment]
@crynobone Yea that worked, thanks!
I've spent a lot of time trying to figure it out, although I was using t he documentation in a step by step, haven't saw any hint about "Your APP_URL should equal to the APP_SERVICE", that would have saved me a lot of time. 

would be great if that can be documented to save time for other people who are using sail, I also notice a lot of people are facing the same issue on my journey of trying to figure this out.

Thanks again. I appreciate your help.
