### ISSUE TITLE
[Feature Request] Assert Message

### ISSUE THREAD

**Issue by mexcoder** [laravel/dusk#206]
Hi, PHPUnit supports an extra argument in all its assertions methods to add a message regarding the error, like [this example](http://www.kreamer.org/phpunit-cookbook/1.0/assertions/display-useful-message-when-test-fails) and as is used on [Concerns/MakesAssertions.php](https://github.com/laravel/dusk/blob/master/src/Concerns/MakesAssertions.php#L252), could this parameter be added to the Dusk's assert methods so we can add our own messages?

**Comment by deleugpn** [comment]
Unfortunately we have messages bound to the method itself. Example: 

```
	public function assertSeeIn($selector, $text)
	{
		$fullSelector = $this->resolver->format($selector);
		
		$element = $this->resolver->findOrFail($selector);
		
		PHPUnit::assertTrue(
			Str::contains($element->getText(), $text),
			"Did not see expected text [{$text}] within element [{$fullSelector}]."
		);
		
		return $this;
	}
```

This could not be replaced with a simple optional parameter `public function assertSeeIn($selector, $text, $message = 'Did not see expected text [{$text}] within element [{$fullSelector}].')` for obvious reasons.

I wouldn't recommend implementing this just for assertions that could simply add a new optional parameter because it could cause inconsistency and I also wouldn't recommend adding if statements through the whole trait just to offer this. 

If you really want something like this, I recommend you to extend the browser class and override all the MakeAssertions methods.

**Comment by driesvints** [comment]
We'll probably not add this but the Browser class is macroable so you should be able to overwrite or add your own methods.
