### ISSUE TITLE
Please also support firefox driver

### ISSUE THREAD

**Issue by fwang-laralabs** [laravel/dusk#612]
Please also support firefox driver.
I have encountered a problem that mouseover does not work.

https://github.com/laravel/dusk/issues/353

**Comment by fwang-laralabs** [comment]
https://medium.com/@melihovv/how-to-use-laravel-dusk-with-selenium-and-firefox-9c12cdf92c94

This document will be used as a reference.
If you have a firefox driver, you're more comfortable.

**Comment by derekmd** [comment]
### Laravel Dusk supporting Geckodriver natively

I created a branch that allows Laravel Dusk to support **geckodriver** (formerly Firefox Driver) without additional configuration: https://github.com/laravel/dusk/compare/6.x...derekmd:firefox-support

```
php artisan dusk:install --firefox
```

will copy a `tests/DuskTestCase.php` into your application that will open Firefox via Geckodriver running at http://localhost:4444/. No Selenium installation is required.

### Geckodriver limitations

Putting this implementation in the "laravel/dusk" package, I see some negatives:

* The developer experience is less rich.
  * There is no JavaScript 'console' log output for debugging.
  * No headless mode for continous integration unless you manually configure a 'xvfb' proxy process.
* There is an additional maintenance burden by adding **geckodriver** binaries and new command `php artisan dusk:firefox-driver`.
  * The https://github.com/mozilla/geckodriver/releases/latest version fetch may stop working similar to the problems with Chromedriver updates in the recent past.
  * As seen in https://github.com/mozilla/geckodriver/releases notes, there are known issues with automating installations:
    * Windows also needs "Microsoft Visual Studio redistributable runtime" to be manually installed separately.
    * macOS Catalina [may have issues](https://firefox-source-docs.mozilla.org/testing/geckodriver/Notarization.html) running the Dusk package's included binaries due to Apple's notarization requirements.

### Laravel Dusk continues only supporting Chromedriver natively

To me, Firefox support in Dusk still seems an edge case for developer power users. The current state doesn't meet Laravel's philosphy of "it just works" for every developer.

I think this issue can be closed since the Dusk docs do have a section on [Using Other Browsers](https://laravel.com/docs/7.x/dusk#using-other-browsers) that shows applications can configure Selenium for switching the target browser to Firefox, Edge, etc.

A middle-ground might be to expand the "Using Other Browsers" docs to include a Geckodriver setup example.

**Comment by driesvints** [comment]
@derekmd thank you so much for looking into this. First of all I want to say that I think it's best that we stop shipping the executables with dusk as they tend to increase the package size by quite a lot. I'm actually thinking of removing the chrome executables in a next major version as well which will require people to always install them with the driver commands.

As for the rest of the PR, I agree that we might best wait until the JavaScript console log issue is resolved. I'll keep this open for the time being but for now it's best that we wait.

**Comment by derekmd** [comment]
> wait until the JavaScript console log issue is resolved

@driesvints: Investigating further, according to Mozilla developer comments in 2018 and 2019, it's a "hard no" on Firefox supporting `$driver->manage()->getLog('browser')` that Laravel Dusk calls when Chrome or PhantomJS browsers are used. This is considered a Selenium spec, outside the scope of the W3C Webdriver API.

References:

* https://bugzilla.mozilla.org/show_bug.cgi?id=1453962
* https://github.com/mozilla/geckodriver/issues/284#issuecomment-456073771
* https://github.com/w3c/webdriver/issues/406

With no active W3C spec discussions or Firefox dev work being done to add `commands.GetLog` to the [WebDriver](https://developer.mozilla.org/en-US/docs/Web/WebDriver) API, the only mechanism Geckodriver consumers are left with is `stdout` logging.

### Possible Laravel Dusk paths

To support Firefox, I see these three options with escalating implementation complexity:

1. Happy path: ignore Firefox browsers ever supporting JavaScript console logging. https://laravel.com/docs/7.x/dusk doesn't even mention this feature so it seems a nice-to-have.
2. Add a `SupportsFirefox` trait method that exposes the `SupportsFirefox::$firefoxProcess->getOutput()` returned string for userland debuggers to call `dump($this->getFirefoxOutput())` after a `$this->browse()` Closure.
3. As mentioned in my previous comment, make Laravel Dusk support two log-fetching paths and both write .log files to the filesystem. I tried this and disliked the final code so much I wiped the commits. `Laravel\Dusk\TestCase` sibling traits need to share state through static methods and it's very ugly.

**Comment by driesvints** [comment]
Thanks for all the research @derekmd. We've decided to not support Firefox for the time being. I'll pin this issue for anyone who wants to know the reasoning.

**Comment by derekmd** [comment]
I've published that "laravel/dusk" dev branch as a standalone package: https://github.com/derekmd/laravel-dusk-firefox

Run these commands to start using Firefox instead of Google Chrome:

```
composer require --dev derekmd/laravel-dusk-firefox
php artisan dusk:install-firefox
php artisan dusk
```

It's also possible to run tests in either browser. See the package's Github docs for more details.
