### ISSUE TITLE
Exception in tearDownDuskClass, Curl error thrown for http DELETE to /session/<session-hash>

### ISSUE THREAD

**Issue by Tarasovych** [laravel/dusk#634]
- Dusk Version: 5.0.2
- Laravel Version: 5.7.28
- PHP Version: 7.2.14
- Database Driver & Version: MySQL 5.7

### Description:

> Exception in Tests\Browser\MyTest::tearDownDuskClass
> Curl error thrown for http DELETE to /session/e76b9bfe8c9f9af519c2901601531c6a
> 
> Operation timed out after 30000 milliseconds with 0 bytes received

### Steps To Reproduce:
```php
class MyTest extends DuskTestCase
{
    use DatabaseMigrations, WithFaker;

    public function testExample()
    {
        $user = \factory(User::class)->create();

        $this->browse(function (Browser $browser) use ($user) {
            $browser
                ->loginAs($user)
                ->visitRoute(/**/)
                ->waitForText(/**/)
                ->type(/**/)
                ->type(/**/)
                ->type(/**/)
                ->attach(/**/, /**/)
                ->press(/**/)
                ->waitForText(/**/)
                ->assertSeeIn(/**/)
                ->click(/**/)
                ->assertSeeIn(/**/)
                ->click(/**/); //new tab is opened

            $windows = collect($browser->driver->getWindowHandles());

            //navigate to new tab
            $browser->driver->switchTo()->window($windows->last());
            $browser->assertPathIs(/**/);
        });
    }
}
```

**Comment by Tarasovych** [comment]
Somehow this made it work
```php
    $window = collect($browser->driver->getWindowHandles())->last(); // last() is called right here
    $browser->driver->switchTo()->window($window);
```

**Comment by Tarasovych** [comment]
Exception is thrown randomly again.

**Comment by driesvints** [comment]
@Tarasovych because the exception is a timeout there's a high chance that this is caused by a heavy process made by the call which causes the call to timeout. This is is hard to debug what's causing this but it's very probably that this isn't caused by Dusk itself. 

You may want to check into https://laravel.com/docs/5.8/dusk#waiting-for-elements or post on a support channel to figure out what the actual problem is. If you can actually identify this as a bug, feel free to report back and I'll gladly help you out.

- [Laracasts Forums](https://laracasts.com/discuss)
- [Laravel.io Forums](https://laravel.io/forum)
- [StackOverflow](https://stackoverflow.com/questions/tagged/laravel)
- [Discord](https://discordapp.com/invite/KxwQuKb)
- [Larachat](https://larachat.co)
- [IRC](https://webchat.freenode.net/?nick=laravelnewbie&channels=%23laravel&prompt=1)

Thanks!

**Comment by An-AngryBear** [comment]
@Tarasovych found any solution yet? I am having the same issue

**Comment by Tarasovych** [comment]
@An-AngryBear to be honest, I can't remind. Probably that was an issue with Chrome itself, you can try different Chrome versions. Let me know, if that helps, otherwise I'll try to dig in.

P. S. Don't even try to create an issue here, Big Brother is watching you, so your issue will be closed asap :D

**Comment by Tarasovych** [comment]
@An-AngryBear for some reason, unfortunately my IDE cache is gone, so I can't look over that test and check the history of the file. Probably, I skipped writing that test at all (my goal was to check that button click opens correct link in the new tab).

I don't know what you were trying to achieve when you faced this problem, if that was opening a page in the new tab, you could try to "assert" that correct page was opened via browser history, if Dusk has such API.

**Comment by mjamshad-ssi** [comment]
Is this the way you solved. If yes, can you please explain where should I add these lines.

![image](https://user-images.githubusercontent.com/59653887/80226928-6c4d1a80-8666-11ea-9c76-57f9dc6e094e.png)
