### ISSUE TITLE
Webdriver error after a few tests

### ISSUE THREAD

**Issue by erksch** [laravel/dusk#680]
- Dusk Version: 5.5.2
- Laravel Version: 5.7.9
- PHP Version: 7.3.5
- Database Driver & Version: mysql 14.14 
- Webdriver version: 1.7.1
- Chromedriver version : 77.0.3865.40 

### Description:
There have been a couple of issues in the past with the chromedriver that only occur after running a few tests in a row. This time with the latest possible versions I get the following warning (which fails my tests) after running multiple tests:

```
Warning: base64_decode() expects parameter 1 to be string, array given in vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php line 363
```

**Comment by driesvints** [comment]
We'll need a lot more info in order to debug this. Can you maybe recreate the issue in a sample repo on github so we can run it?

**Comment by driesvints** [comment]
Closing this issue because it's inactive, already solved, old or not relevant anymore. Feel free to reply if you're still experiencing this issue and we'll re-open this issue.

**Comment by klimov-paul** [comment]
Such issue happens from time to time, in case of browser session problem.
In my case Web driver ends up with the following exception:

```
Facebook\WebDriver\Exception\UnknownServerException: unknown error: session deleted because of page crash
```

However, with current codebase you are unable to see such error message, seeing the following one instead:

```
Warning: base64_decode() expects parameter 1 to be string, array given in vendor/facebook/webdriver/lib/Remote/RemoteWebDriver.php line 363
```

This happens at the stage when Dusk attempts to make a screenshot of the page failure at `Laravel\Dusk\Browser::screenshot()` method, invoking the line 298:

```php
$this->driver->takeScreenshot($filePath);
```

Then remote web driver execute command `DriverCommand::SCREENSHOT` expecting it to return a string, but due to driver session failure it returns a following array instead:

```
Array
(
    [error] => invalid session id
    [message] => invalid session id
    [stacktrace] => #0 0x5610a5d2d959 <unknown>
)
```

This might be considered as a Facebook driver bug.
Still it can be easily avoided wrapping screenshot making code into `try catch` block:

```php
class Browser
{
    // ...
    public function screenshot($name)
    {
        $filePath = sprintf('%s/%s.png', rtrim(static::$storeScreenshotsAt, '/'), $name);

        $directoryPath = dirname($filePath);

        if (! is_dir($directoryPath)) {
            mkdir($directoryPath, 0777, true);
        }

        try {
            $this->driver->takeScreenshot($filePath);
        } catch (\Throwable $e) {
            // handle problem without script unexpected stop, like log, output to stderr or something
        }

        return $this;
    }
    // ...
}
```

In this way error appearing while taking a screenshot will not hide real problem from the developer.

**Comment by klimov-paul** [comment]
This issue can be reproduced running Dusk test against page causing a JavaScript error, which is considered as a "page crash" by Facebook Driver.

**Comment by demisolutions** [comment]
In my case problem went away after I increase shm_size in docker container (64MB was too low for specific tests). 

If you will be increasing shm_size in docker, make sure to change it on service AND build level  and then re-run container :)
