### ISSUE TITLE
assertFocused() does not work in W3C mode

### ISSUE THREAD

**Issue by alecpl** [laravel/dusk#736]
Looks like webdriver is switching to W3C mode. According to https://github.com/php-webdriver/php-webdriver/blob/7729633d3b7068a62e76adc4b784eb78f8dec9ec/lib/Remote/RemoteWebElement.php#L466 `equals()` method should not be used. And it is used in `assertFocused()` and `assertNotFocused()`

I know you switched back to older webdriver version, but this will have to be fixed. This is the trace I got (before composer update):
```
Facebook\WebDriver\Exception\UnsupportedOperationException: "elementEquals" is not supported by the W3C specification

/home/travis/build/roundcube/roundcubemail/vendor/facebook/webdriver/lib/Remote/RemoteWebElement.php:466
/home/travis/build/roundcube/roundcubemail/vendor/laravel/dusk/src/Concerns/MakesAssertions.php:709
...
```

**Comment by driesvints** [comment]
Any bug made through the 1.8.0 update of php-webdriver should be reported to them. When a minor update is done everything should still work in a backwards compatible way. W3C mode is a new modus in their 1.8.0 update and Dusk doesn't provides full support for this yet. You're free to help out with sending in a PR if you want. Thanks.

**Comment by alecpl** [comment]
I do not agree. If dusk is not compatible with newer webdriver version, it's not webdriver's fault. Even if that could/should be fixed on webdriver's side, I think it is dusk developers responsibility to take care of this issue.

Some comments I saw suggest that they will not revert to non-W3C mode. So, whenever dusk decides to use newer version in the future you will have to disable that mode or not use `equals()` method. So, it seams reasonable to keep that warning as an open issue. Finally, if I'm first person noticing this issue (and I didn't find other ticket), then maybe your tests do not cover that case properly.

I'm really disappointed by the attitude here.

**Comment by driesvints** [comment]
@alecpl you're free to send in a PR if you want

**Comment by OndraM** [comment]
Hi @alecpl, we reintroduced `equals()` support in W3C mode of php-webdriver in https://github.com/php-webdriver/php-webdriver/pull/769 (this could be done because this specific feature can be easily reimplemented client-side, even though it was removed from the protocol). 

Please understand W3C protocol implementation was quite a big job for few volunteers working on php-webdriver, and not everything may be 100 % polished - and help is always welcomed.

However thanks for pointing this out, it will be part of next php-webdriver release :ok_hand: .

**Comment by alecpl** [comment]
@driesvints Could you re-open this ticket? It is now a real issue in v5.9.2. You unlocked the php-webdriver version in 116b3da458 despite me warning you here that it will cause issues. The fix mentioned above wasn't yet released.

**Comment by driesvints** [comment]
@alecpl as I mentioned before this is a problem with the problem within php-webdriver. It'll be fixed one the fix above is tagged. We can update the minimum required version when that has happened.

@OndraM thanks for that 👍

**Comment by OndraM** [comment]
@alecpl If you need to fix it ASAP, I guess you can *temporarily* overwrite php-webdriver dependency to use `master` branch version. In your composer.json require section add something like:

```json
"require" : {
    "php-webdriver/webdriver": "dev-master as 1.8.2",
}
```
and run `composer update`. (but don't forget to remove this once the new version of php-webdriver is tagged, otherwise you will continue to use `master` branch).

**Comment by alecpl** [comment]
I know how to fix it. My point is that v5.9.2 is a buggy release right now. I did composer update today and my tests stopped working. Either you're not testing your code properly or there's some test missing otherwise it should not happen.

**Comment by lk77** [comment]
Hello,

any news on this issue ?

**Comment by OndraM** [comment]
Php-webdriver 1.8.2 has been released literally minutes ago, so you were most probably not using it.

Try running `composer update` and make sure `composer show php-webdriver/webdriver` output version 1.8.2.
