### ISSUE TITLE
Laravel 9/Inertia/Vue3/Sail/Dusk setup requires that the vite dev server is not running

### ISSUE THREAD

**Issue by maxheckel** [laravel/dusk#992]
- Dusk Version:  6.25.1
- Laravel Version: 9.23.0
- PHP Version: 8.1.8
- Inertia Version: 0.5.4
- Database Driver & Version:  n/a

### Description:
FYI, I don't think this is an issue so much as it's not documented that you should not run vite when running dusk tests. 

If you're running the vite dev server (via ./vendor/bin/sail npm run dev) and attempt to run dusk (via ./vendor/bin/sail dusk) chromium will fail to find the built assets.  Console errors as following:

```
[
    {
        "level": "SEVERE",
        "message": "http:\/\/0.0.0.0:5173\/@vite\/client - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1660421297858
    },
    {
        "level": "SEVERE",
        "message": "http:\/\/0.0.0.0:5173\/resources\/js\/app.js - Failed to load resource: net::ERR_CONNECTION_REFUSED",
        "source": "network",
        "timestamp": 1660421297858
    }
]
```

### Steps To Reproduce:
Setup laravel with inertia, vue3 and sail on a Mac M1.  Start the vite dev server with `/vendor/bin/sail npm run dev`, attempt to run dusk in the sail container `/vendor/bin/sail dusk`, see it fail to render any of the JS.

**Comment by DarkGhostHunter** [comment]
It seems that this should be fixable by allowing dusk to build the assets _before_ running. I don't know if it would be detrimental if Vite doesn't cache builds.

**Comment by maxheckel** [comment]
> It seems that this should be fixable by allowing dusk to build the assets _before_ running. I don't know if it would be detrimental if Vite doesn't cache builds.

Yes! That would be ideal, right now I essentially have to run `sail npm run build` prior to every run if I make changes

**Comment by timacdonald** [comment]
Hey folks,

I would not recommend running the Vite dev server while also trying to run your dusk tests.

Although some Docker peeps may be able to get it to work, due to the complexities of Docker networking, it isn't going to be easy. We would, however, be open to a PR if there is an elegant solution to this that we are just not aware of.

I would also imagine if you are running Dusk tests to "get closer to the real world", running the dev server is kinda an anti-pattern, as it works very differently to plain built assets and could result in false positives, as the Vite server will essentially deliver any resource it finds, whether it is actually in the build or not, so again, use the dev server in *any* tests with caution.

Instead, if you wish to automate this process in your own application, I would recommend doing the following:

```php
abstract class DuskTestCase extends BaseTestCase
{
    /* ... */

    protected static $assetsBuilt = false;

    /**
     * Prepare for Dusk test execution.
     *
     * @beforeClass
     * @return void
     */
    public static function prepare()
    {
        if (! self::$assetsBuilt) {
            if (is_file('public/hot')) {
                dd('You should stop the Vite dev server.');
            }

            echo 'Compiling front-end assets.'.PHP_EOL;
            exec('npm run build');
            echo 'Front-end assets compiled.'.PHP_EOL;

            self::$assetsBuilt = true;
        }

        if (! static::runningInSail()) {
            static::startChromeDriver();
        }
    }

    /* ... */
}
```

Hope this gets you back on track!
